version: '2.1'

services:
  mysql:
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    container_name: 'wiki-nginx'
    volumes:
      - mediawiki-volume:/srv/mediawiki
    networks:
      nginx-network:
  php:
    volumes:
      - mediawiki-volume:/srv/mediawiki
  mediawiki:
    volumes:
      - mediawiki-volume:/srv/mediawiki

volumes:
  mediawiki-volume:
  db-volume:

networks:
  nginx-network:
